Task4
ivocat/testguru pull request #3
Opened 2018-05-28 19:02 UTC by ivocat

2018-05-29 09:18 UTC, psylone requested changes

2018-05-29 09:18 UTC, psylone commented on app/models/user.rb
> +    tests.where(level: level)
Проверь этот метод в консоли.

2018-05-29 09:18 UTC, psylone commented on app/models/test.rb
> +    tests.where(category_id: categories.find_by(name: category_name).id).order(title: :desc)
Здесь необходимо вернуть массив названий тестов.

2018-05-29 09:18 UTC, psylone commented on app/models/test.rb
> +    tests.where(category_id: categories.find_by(name: category_name).id).order(title: :desc)
Также пожалуйста проверь как работает этот метод.

2018-06-06 08:24 UTC, psylone requested changes

2018-06-06 08:24 UTC, psylone commented on app/models/user.rb
> +    Test.where(level: level)
Хорошо, но необходимо выбрать именно те тесты определённого уровня которые проходит **конкретный** пользователь.

2018-06-06 08:24 UTC, psylone commented on app/models/test.rb
> +    Test.where(category_id: Category.find_by(name: category_name).id).order(title: :desc).to_a
Попробуй сделать так чтобы метод отрабатывал за один SQL запрос. Также смысл массива в том чтобы возвращался именно массив названий тестов, а не массив объектов тестов.

2018-06-07 19:39 UTC, iBublik approved these changes

2018-06-07 19:39 UTC, iBublik commented on app/models/test.rb
> +  def self.list_tests_by_category(category_name)
В названии метода не стоит дублировать название класса. Так же не стоит испольховать название возвращаемых структур (иначе при смене используемой структуры придется и имя метода везде менять). `by_category` будет вполне достаточно.

2018-06-07 19:39 UTC, iBublik commented on app/models/test.rb
> +      WHERE categories.name = '#{category_name}';")
Условие может быть сгенерировано рельсами - `where(categories: { name: category_name })`. Так же нельзя использовать ; в запросах, написанных вручную - для многих СУБД это признак конца запроса.

2018-06-07 19:39 UTC, iBublik commented on app/models/user.rb
> +  def list_tests_with_level(level)
list в названии лишнее

2018-06-07 19:39 UTC, iBublik commented on app/models/user.rb
> +    self_id = self.id
Зачем под это переменную отводить?

2018-06-07 19:39 UTC, iBublik commented on app/models/user.rb
> +    .where("user_id = ? AND status != 'None' AND level = ?", self_id, level)
Делегируй максимум работы рельсам, пускай они за тебя запросы генерируют - `where(user_id: id, tests: { level: level })`
Про статусы - у нас в принципе такого поля не будет, но если очень хочется - оставь. Могу лишь посоветовать хранить в базе не человеко-читаемую строку, а некий текстовый идентификатор (in_progress вместо In Progress и т.п.).

2018-06-10 19:35 UTC, merged